/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Record = IDL.Record({
  'latitude' : IDL.Float64,
  'city' : IDL.Text,
  'longitude' : IDL.Float64,
  'inCelsius' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getAllPreferences' : IDL.Func([], [IDL.Vec(Record)], ['query']),
  'getPreferences' : IDL.Func([], [Record], ['query']),
  'savePreferences' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Record = IDL.Record({
    'latitude' : IDL.Float64,
    'city' : IDL.Text,
    'longitude' : IDL.Float64,
    'inCelsius' : IDL.Bool,
  });
  
  return IDL.Service({
    'getAllPreferences' : IDL.Func([], [IDL.Vec(Record)], ['query']),
    'getPreferences' : IDL.Func([], [Record], ['query']),
    'savePreferences' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };